// LOCALHOST 

### Get all users GET http://localhost:8080/users

### Create users POST http://localhost:8080/users

{
    "firstName":"Tony", 
    "lastName":"Hanks", 
    "email":"hanks@test.com", 
    "favoriteColor":"Brown", 
    "birthday":"06/19/2000"
}

### PUT users PUT http://localhost:8080/users/6408c278485d8a3f7da65e3a

{
    "firstName":"Taylor", 
    "lastName":"Eakins", 
    "email":"test@gmail.com", 
    "favoriteColor":"Green", 
    "birthday":"12/12/20"
} 

### DELETE users DELETE http://localhost:8080/users/6408c23e485d8a3f7da65e36 



// PRODUCTION Deploy 
### Get all users GET https://cse341-lesson-05.onrender.com/users

### Create users POST https://cse341-lesson-05.onrender.com/users

{
    "firstName":"Ashley", 
    "lastName":"Weaver",
    "email":"posttest@test.com", 
    "favoriteColor":"Brown", 
    "birthday":"06/19/2000"
}

### PUT users PUT https://cse341-lesson-05.onrender.com/users/6408c27e485d8a3f7da65e3c

{
    "firstName":"Sarah", 
    "lastName":"Birch",
    "email":"puttesst@gmail.com",
    "favoriteColor":"Yellow", 
    "birthday":"06/12/20"
}

### DELETE users DELETE https://cse341-lesson-05.onrender.com/users/6408c244485d8a3f7da65e38