// LOCALHOST 

### Get all users GET http://localhost:8080/users

### Get one users GET http://localhost:8080/users/6412a348b4ddb25cf52c91db

### Create users POST http://localhost:8080/users

{
    "firstName":"Tony", 
    "lastName":"Hanks", 
    "email":"hanks@test.com",
    "password": "$ecretPassword",
    "birthday": "06/06/1994",
    "phone": "1234567890",
    "address": "Puerto Ordaz",
}

### PUT users PUT http://localhost:8080/users/640becf31fffa971db2d902f

{
    "firstName":"Taylor", 
    "lastName":"Eakins", 
    "email":"test@gmail.com", 
    "birthday": "06/06/1994",
    "phone": "1234567890",
    "address": "Puerto Ordaz"
} 

### DELETE users DELETE http://localhost:8080/users/640bf2bae949b1c45aeddc1b 



// PRODUCTION Deploy 
### Get all users GET https://cse341-lesson-06.onrender.com/users

### Get one users GET https://cse341-lesson-06.onrender.com/users/640bf3f6e949b1c45aeddc31

### Create users POST https://cse341-lesson-06.onrender.com/users

{
    "firstName":"Ashley", 
    "lastName":"Weaver",
    "email":"posttest@test.com",
    "password": "$ecretPassword", 
    "birthday": "06/06/1994",
    "phone": "1234567890",
    "address": "Puerto Ordaz"
}

### PUT users PUT https://cse341-lesson-06.onrender.com/users/640bf3c4e949b1c45aeddc27

{
    "firstName":"Sarah", 
    "lastName":"Birch",
    "email":"puttesst@gmail.com",
    "birthday": "06/06/1994",
    "phone": "1234567890",
    "address": "Puerto Ordaz"
}

### DELETE users DELETE https://cse341-lesson-06.onrender.com/users/640bf3d8e949b1c45aeddc2a